#spring.application.name=application
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacydb?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # can be 'update', 'create', 'create-drop', 'none'
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
